### ISSUE TITLE
the link of zhihu provided in readme is invalid

### ISSUE THREAD

**Issue by yhpan** [kongdd/gee_whittaker#1]
I want to know how to use Whittaker in Google Earth Engine (GEE), so i click the ‘知乎’ link you provided in readme. but it seems invalid.

**Comment by kongdd** [comment]
It is at here, https://kongdd.github.io/2019/08/03/gee-whittaker-smoother/

**Comment by yhpan** [comment]
> It is at here, https://kongdd.github.io/2019/08/03/gee-whittaker-smoother/

very grateful
