### ISSUE TITLE
GEE: Cannot find required repo

### ISSUE THREAD

**Issue by Mew-YL** [kongdd/gee_whittaker#3]
Recently I want to do something with time series smoothing in GEE and I found the script you've shared https://code.earthengine.google.com/578677be7dd86fd6a489cb0adb0b7d36
but I ran into the error in GEE when runing this code 
> 'Cannot find required repo: users/kongdd/public:Math/pkg_whit.js'. 

Is there anyway to solve this?

**Comment by DimitrisKasabalis** [comment]
Did you find a solution or get the missing file?

**Comment by sak-18** [comment]
Same issue, any leads?
