### ISSUE TITLE
Cannot find required repo: users/kongdd/public:pkg_export.js

### ISSUE THREAD

**Issue by ITzzF** [kongdd/gee_whittaker#4]
老师您好，关于在GEE运行代码，这个问题怎么解决？麻烦老师指导

**Comment by kongdd** [comment]
改成：`users/kongdd/pkgs:pkg_export.js`

**Comment by ITzzF** [comment]
老师您好，还想继续请教这个问题，我对这个错误进行了修改，然后代码还是会出现类似的错误，修改部分代码之后还是会报错，如下图所示。代码链接为：https://code.earthengine.google.com/46813e807b1079cdf4bd27e2b3970faf
![image](https://github.com/user-attachments/assets/203b83d0-474f-4fb2-a4c1-e694db900804)

**Comment by KagariWorld** [comment]
兄弟，请问你解决了吗
